import { Manga } from "../types";

export const MOCK_MANGAS: Manga[] = [
  {
    id: "manga-1",
    title: "One Piece",
    synopsis:
      "Monkey D. Luffy sueña con convertirse en el Rey de los Piratas. Tras comer una Fruta del Diablo que le otorga un cuerpo de goma, parte en busca del legendario tesoro One Piece junto a su variopinta tripulación, los Piratas de Sombrero de Paja.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx96792-hqZV0JqlBsW4.jpg",
    genres: ["Acción", "Aventura"],
    status: "En emisión",
    year: 1997,
    chaptersCount: 1110,
    rating: 9.5,
  },
  {
    id: "manga-2",
    title: "Berserk",
    synopsis:
      "Guts, un mercenario solitario con una espada descomunal, lucha por su supervivencia en un mundo medieval oscuro y brutal. Marcado por el destino y traicionado por su mejor amigo, busca venganza mientras es perseguido por demonios.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30002-Cul4OeN7bYtn.jpg",
    genres: ["Acción", "Fantasía Oscura"],
    status: "En emisión",
    year: 1989,
    chaptersCount: 374,
    rating: 9.8,
  },
  {
    id: "manga-3",
    title: "Vagabond",
    synopsis:
      "Basado en la vida del legendario espadachín Miyamoto Musashi, narra su búsqueda de la invencibilidad a través de innumerables duelos en el Japón del período Edo. Una historia sobre la guerra, la filosofía y el autodescubrimiento.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30023-NWoD28ZKC73c.jpg",
    genres: ["Acción", "Histórico"],
    status: "Finalizado",
    year: 1998,
    chaptersCount: 327,
    rating: 9.5,
  },
  {
    id: "manga-4",
    title: "Vinland Saga",
    synopsis:
      "Thorfinn, hijo de un gran guerrero vikingo, busca venganza contra el mercenario que mató a su padre. Ambientada en la época vikinga, explora la violencia, la guerra y el camino hacia una verdadera tierra de paz: Vinland.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/17065.jpg",
    genres: ["Acción", "Histórico"],
    status: "En emisión",
    year: 2005,
    chaptersCount: 210,
    rating: 9.3,
  },
  {
    id: "manga-5",
    title: "Fullmetal Alchemist",
    synopsis:
      "Los hermanos Edward y Alphonse Elric intentan recuperar sus cuerpos perdidos tras un fallido intento de resurrección usando alquimia. Su búsqueda de la Piedra Filosofal los arrastra a una vasta conspiración que sacude los cimientos del estado.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30025-mpPVpCKFTowt.png",
    genres: ["Acción", "Aventura"],
    status: "Finalizado",
    year: 2001,
    chaptersCount: 116,
    rating: 9.4,
  },
  {
    id: "manga-6",
    title: "Monster",
    synopsis:
      "El brillante neurocirujano Kenzou Tenma salva la vida de un niño en lugar de un importante político, decisión que arruina su carrera. Años después descubre que ese niño se ha convertido en un asesino en serie, desencadenando una persecución moral y existencial.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30001-Knby7l1jevE7.jpg",
    genres: ["Misterio", "Drama"],
    status: "Finalizado",
    year: 1994,
    chaptersCount: 162,
    rating: 9.3,
  },
  {
    id: "manga-7",
    title: "20th Century Boys",
    synopsis:
      "Kenji Endo descubre que un culto misterioso y su líder, conocido como 'Amigo', planea destruir el mundo usando planes sacados de un libro de ficción que él mismo escribió de niño. Una conspiración que une el pasado y el futuro de la humanidad.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30008-gETc2OY1tby1.jpg",
    genres: ["Misterio", "Drama"],
    status: "Finalizado",
    year: 1999,
    chaptersCount: 249,
    rating: 9.2,
  },
  {
    id: "manga-8",
    title: "Chainsaw Man",
    synopsis:
      "Denji, un joven en deuda con la yakuza, se fusiona con su perro demonio Pochita para convertirse en el Hombre Motosierra. Reclutado por los Cazadores Públicos de Demonios, debe enfrentarse a amenazas sobrenaturales en un mundo donde los demonios nacen del miedo.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx105778-euxXZEIfDY2u.png",
    genres: ["Acción", "Horror"],
    status: "En emisión",
    year: 2018,
    chaptersCount: 160,
    rating: 9.0,
  },
  {
    id: "manga-9",
    title: "Jujutsu Kaisen",
    synopsis:
      "Yuji Itadori, un chico de fuerza sobrehumana, ingiere un dedo del poderoso espíritu maldito Ryomen Sukuna para salvar a sus compañeros. Desde ese momento se convierte en anfitrión del demonio más peligroso y entra al mundo de los hechiceros de jujutsu.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx104050-7SS19qVOCeZl.png",
    genres: ["Acción", "Sobrenatural"],
    status: "Finalizado",
    year: 2018,
    chaptersCount: 270,
    rating: 9.1,
  },
  {
    id: "manga-10",
    title: "Kimetsu no Yaiba",
    synopsis:
      "Tanjiro Kamado regresa a casa para encontrar a su familia masacrada por un demonio. Su hermana Nezuko, la única sobreviviente, se ha convertido en demonio. Determinado a curarla y vengar a su familia, se convierte en un cazador de demonios.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx87216-c9bSNVD10UuD.png",
    genres: ["Acción", "Sobrenatural"],
    status: "Finalizado",
    year: 2016,
    chaptersCount: 205,
    rating: 8.9,
  },
  {
    id: "manga-11",
    title: "Shingeki no Kyojin",
    synopsis:
      "En un mundo donde la humanidad vive encerrada tras enormes murallas para protegerse de los Titanes, gigantes humanoides que devoran personas, Eren Yeager jura exterminarlos a todos tras presenciar la caída de su ciudad natal.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx53390-1RsuABC34P9D.jpg",
    genres: ["Acción", "Drama"],
    status: "Finalizado",
    year: 2009,
    chaptersCount: 141,
    rating: 9.2,
  },
  {
    id: "manga-12",
    title: "Hunter x Hunter",
    synopsis:
      "Gon Freecss descubre que su padre, al que creía muerto, es en realidad un Hunter legendario. Decide convertirse en Hunter también para encontrarlo, embarcándose en peligrosas aventuras junto a sus amigos Killua, Kurapika y Leorio.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx31477-EogTyyihMhQo.png",
    genres: ["Acción", "Aventura"],
    status: "En emisión",
    year: 1998,
    chaptersCount: 400,
    rating: 9.3,
  },
  {
    id: "manga-13",
    title: "Dragon Ball",
    synopsis:
      "Son Goku, un niño con rabo de mono y una fuerza extraordinaria, parte en busca de las siete Esferas del Dragón. A lo largo de su aventura se enfrenta a rivales cada vez más poderosos y descubre su origen extraterrestre como guerrero Saiyan.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30042-4SetGiEbGc9x.jpg",
    genres: ["Acción", "Aventura"],
    status: "Finalizado",
    year: 1984,
    chaptersCount: 519,
    rating: 9.1,
  },
  {
    id: "manga-14",
    title: "Naruto",
    synopsis:
      "Naruto Uzumaki es un joven ninja del pueblo de Konoha que lleva sellado en su interior al poderoso Zorro de Nueve Colas. Rechazado por la aldea, sueña con convertirse en Hokage para ganarse el reconocimiento de todos.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx30011-9yUF1dXWgDOx.jpg",
    genres: ["Acción", "Aventura"],
    status: "Finalizado",
    year: 1999,
    chaptersCount: 700,
    rating: 8.8,
  },
  {
    id: "manga-15",
    title: "Bleach",
    synopsis:
      "Ichigo Kurosaki adquiere accidentalmente los poderes de un Shinigami —un Dios de la Muerte— al absorber los de Rukia Kuchiki. Con estos poderes protege a los humanos de los Hollows y lidia con las complejas jerarquías del mundo espiritual.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30012-1epmVfTSv2rr.png",
    genres: ["Acción", "Sobrenatural"],
    status: "Finalizado",
    year: 2001,
    chaptersCount: 686,
    rating: 8.7,
  },
  {
    id: "manga-16",
    title: "Solo Leveling",
    synopsis:
      "Sung Jin-Woo es considerado el cazador más débil de la humanidad. Tras sobrevivir a una mazmorra mortal, obtiene el poder único de subir de nivel indefinidamente en un mundo donde los portales a mazmorras llenas de monstruos amenazan la civilización.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx121496-oroRMihRAA89.jpg",
    genres: ["Acción", "Fantasía"],
    status: "Finalizado",
    year: 2018,
    chaptersCount: 179,
    rating: 9.0,
  },
  {
    id: "manga-17",
    title: "Boku no Hero Academia",
    synopsis:
      "En un mundo donde el 80% de la población posee superpoderes llamados 'Quirks', Izuku Midoriya nace sin ninguno. Sin embargo, su ídolo, el mayor héroe del mundo, le transmite su poder único, abriéndole el camino para convertirse en un héroe profesional.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx75657-PMv4teU6DuaI.jpg",
    genres: ["Acción", "Superhéroes"],
    status: "En emisión",
    year: 2014,
    chaptersCount: 430,
    rating: 8.6,
  },
  {
    id: "manga-18",
    title: "Black Clover",
    synopsis:
      "Asta, nacido sin magia en un mundo donde todos la poseen, sueña con convertirse en el Rey Mago. Armado con una espada capaz de anular la magia y una voluntad inquebrantable, lucha junto a su hermano adoptivo Yuno para alcanzar la cima.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx85613-TrfuOHd0QWvX.jpg",
    genres: ["Acción", "Magia"],
    status: "En emisión",
    year: 2015,
    chaptersCount: 380,
    rating: 8.4,
  },
  {
    id: "manga-19",
    title: "Fairy Tail",
    synopsis:
      "Lucy Heartfilia, una joven maga invocadora de espíritus estelares, se une al famoso y caótico gremio de magos Fairy Tail. Junto a Natsu Dragneel y sus amigos, vive aventuras épicas que ponen a prueba los lazos de amistad y la magia.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/92603-kNSnvE6m9A7X.jpg",
    genres: ["Acción", "Aventura"],
    status: "Finalizado",
    year: 2006,
    chaptersCount: 545,
    rating: 8.5,
  },
  {
    id: "manga-20",
    title: "Sword Art Online",
    synopsis:
      "En el año 2022, miles de jugadores quedan atrapados dentro del videojuego de realidad virtual Sword Art Online. La única forma de escapar es llegar al piso 100 del castillo Aincrad, pero morir en el juego significa morir en la vida real.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/30897.jpg",
    genres: ["Acción", "Isekai"],
    status: "Finalizado",
    year: 2012,
    chaptersCount: 27,
    rating: 7.9,
  },
  {
    id: "manga-21",
    title: "Re:Zero",
    synopsis:
      "Subaru Natsuki es transportado a otro mundo de manera inesperada. Pronto descubre que posee el poder de 'Volver a la Muerte': cada vez que muere, regresa a un punto anterior en el tiempo. Con este don y su maldición, debe proteger a las personas que ama.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx84577-Xb1c65kFvrnm.png",
    genres: ["Isekai", "Drama"],
    status: "En emisión",
    year: 2014,
    chaptersCount: 90,
    rating: 8.5,
  },
  {
    id: "manga-22",
    title: "Tokyo Ghoul",
    synopsis:
      "Ken Kaneki, un estudiante universitario normal, sobrevive a un ataque de una ghoul y se convierte en mitad ghoul. Atrapado entre dos mundos, debe aprender a vivir en las sombras de Tokio, donde los ghouls se alimentan de carne humana para sobrevivir.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx53304-CPtLaZ653KSI.jpg",
    genres: ["Horror", "Acción"],
    status: "Finalizado",
    year: 2011,
    chaptersCount: 143,
    rating: 8.7,
  },
  {
    id: "manga-23",
    title: "Spy x Family",
    synopsis:
      "El espía de élite conocido como Loid Forger debe crear una familia falsa para completar una misión encubierta. Adopta a una niña telepática y se casa con una asesina, sin saber que cada uno oculta secretos que, paradójicamente, los mantienen unidos.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx108556-NHjkz0BNJhLx.jpg",
    genres: ["Comedia", "Acción"],
    status: "En emisión",
    year: 2019,
    chaptersCount: 100,
    rating: 9.0,
  },
  {
    id: "manga-24",
    title: "Dandadan",
    synopsis:
      "Momo Ayase cree en los fantasmas pero no en los alienígenas, mientras que Ken Okarun cree en los alienígenas pero no en los fantasmas. Un día ambos se ven arrastrados a un mundo sobrenatural lleno de entidades paranormales y extraterrestres en una historia absurda y llena de acción.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx132029-prGF4gePdSKv.jpg",
    genres: ["Sobrenatural", "Comedia"],
    status: "En emisión",
    year: 2021,
    chaptersCount: 170,
    rating: 9.0,
  },
  {
    id: "manga-25",
    title: "Oshi no Ko",
    synopsis:
      "Un médico obsesionado con la idol Ai Hoshino renace como su propio hijo. Junto a su hermana gemela, crece en el mundo del espectáculo japonés descubriendo sus oscuros secretos, mientras busca la verdad detrás del asesinato de su madre.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx117195-r3kf8eF0xkDJ.png",
    genres: ["Drama", "Misterio"],
    status: "En emisión",
    year: 2020,
    chaptersCount: 160,
    rating: 9.1,
  },
  {
    id: "manga-26",
    title: "Mushoku Tensei",
    synopsis:
      "Un hombre de 34 años sin trabajo ni futuro muere y renace en un mundo de magia y espadas como Rudeus Greyrat, conservando todos sus recuerdos. Decidido a no desperdiciar esta segunda oportunidad, se convierte en un prodigioso mago.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx85564-egXRASF0x9B9.jpg",
    genres: ["Isekai", "Aventura"],
    status: "En emisión",
    year: 2014,
    chaptersCount: 110,
    rating: 8.8,
  },
  {
    id: "manga-27",
    title: "Tensei Shitara Slime Datta Ken",
    synopsis:
      "Satoru Mikami, un oficinista de 37 años, muere apuñalado y renace en un mundo de fantasía como un slime. Con la habilidad única de absorber y replicar cualquier cosa que devore, construye su propio país de monstruos y se convierte en una gran leyenda.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx114571-FizKP6E6RHVy.png",
    genres: ["Isekai", "Fantasía"],
    status: "En emisión",
    year: 2015,
    chaptersCount: 140,
    rating: 8.6,
  },
  {
    id: "manga-28",
    title: "Slam Dunk",
    synopsis:
      "Hanamichi Sakuragi, un delincuente juvenil de dos metros rechazado por todas las chicas, se une al equipo de baloncesto de su escuela secundaria para conquistar a Haruko. Lo que comienza como una farsa se convierte en una pasión genuina por el deporte.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30043-b2SqUjwSzfIH.png",
    genres: ["Deporte", "Drama"],
    status: "Finalizado",
    year: 1990,
    chaptersCount: 276,
    rating: 9.1,
  },
  {
    id: "manga-29",
    title: "Death Note",
    synopsis:
      "Light Yagami, un estudiante de secundaria con notas perfectas, encuentra un cuaderno sobrenatural que mata a cualquier persona cuyo nombre sea escrito en él. Decide usarlo para crear un mundo libre de criminales, mientras el detective L intenta atraparle.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30021-FE6kmrfpuKyb.jpg",
    genres: ["Thriller", "Misterio"],
    status: "Finalizado",
    year: 2003,
    chaptersCount: 108,
    rating: 9.2,
  },
  {
    id: "manga-30",
    title: "Frieren: Beyond Journey's End",
    synopsis:
      "Frieren, una elfa maga que participó en el grupo de héroes que derrotó al Rey Demonio, regresa décadas después para reencontrarse con sus compañeros, solo para descubrir que el tiempo los ha envejecido. Embarca en un nuevo viaje para comprender a la humanidad.",
    coverUrl: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx118586-CXKgWikBFQgS.jpg",
    genres: ["Fantasía", "Aventura"],
    status: "En emisión",
    year: 2020,
    chaptersCount: 120,
    rating: 9.3,
  },
];
